# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f116445f877cba99d6687ae59e810ec54dc8d94bd127041cbd81d79ed034b8d133d1de248e4489dfd15da0d773438284579ed891d323bd7c15836681ba5634a

test:
  secret_key_base: 26a38efbea60c44af930d501712382d9a37ba923265d770c53fe9145c41d893e00102650b651a4b2001af3376e94adc09581cd121246ec96e2aa3423805e0e0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
